name: CI
on:
  pull_request:

concurrency:
  group: ci-yaml-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-js-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Installing dependencies
        run: npm install && npx playwright install --with-deps && cargo install cargo-component
      - name: Building Rust code and JS bindings
        run: npm run build
      - name: Linting Rust code
        run: cargo clippy -- -D warnings
      - name: Testing JS bindings
        run: npm run test
