name: Publish to NPM
# Eventually we want this to run when a new release is cut, but temporarily
# making it manual for testing purposes
# on:
#   release:
#     types: [created]
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          token: ${{ secrets.NPM_AWS_WASM_CHECKSUMS_PUBLISH }}
      - name: Install dependencies
        run: npm install && cargo install cargo-component
      - name: Build package
        run: npm run build
      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AWS_WASM_CHECKSUMS_PUBLISH }}
